version: '3.9'

services:
  n8n:
    image: n8nio/n8n:stable
    ports:
      - "5678:5678"
    networks:
      - traefik
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=user
      - N8N_BASIC_AUTH_PASSWORD=password
      - N8N_SECURE_COOKIE=false
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=10.250.0.68
      - DB_POSTGRESDB_PORT=5003
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=flexxus
      - DB_POSTGRESDB_PASSWORD=Flexxus2023**
      - NODE_FUNCTION_ALLOW_EXTERNAL=axios,qs
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST=smtp.gmail.com
      - N8N_SMTP_PORT=465
      - N8N_SMTP_USER=alezagalia@gmail.com
      - N8N_SMTP_PASS=ypva dgqy tbcu ytxa
      - N8N_SMTP_SENDER=alezagalia@gmail.com
      - N8N_SMTP_SSL=true
      - WEBHOOK_URL=https://n8n.flexxus.com.ar/
      - N8N_HOST=n8n.flexxus.com.ar
      - N8N_PORT=5678
      - N8N_PROTOCOL=https 
    restart: unless-stopped
    deploy:
      placement:
        constraints: ["${NODE}"]  
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${SERVICE_NAME}.entrypoints=web"
        - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${DOMAIN_NAME}`)"
        - "traefik.http.middlewares.${SERVICE_NAME}-http.redirectscheme.scheme=https"
        - "traefik.http.routers.${SERVICE_NAME}-https.rule=Host(`${DOMAIN_NAME}`)"
        - "traefik.http.routers.${SERVICE_NAME}-https.entrypoints=https"
        - "traefik.http.routers.${SERVICE_NAME}-https.tls=true"
        - "traefik.http.routers.${SERVICE_NAME}-https.tls.certresolver=myresolver"
        - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=5678"     
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL} 
networks:
  traefik:
    external:
      name: traefik
